export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST'
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS'
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL'

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST'
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS'
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL'

export const TEST_DELETE_REQUEST = 'TEST_DELETE_REQUEST'
export const TEST_DELETE_SUCCESS = 'TEST_DELETE_SUCCESS'
export const TEST_DELETE_FAIL = 'TEST_DELETE_FAIL'

export const TEST_CREATE_REQUEST = 'TEST_CREATE_REQUEST'
export const TEST_CREATE_SUCCESS = 'TEST_CREATE_SUCCESS'
export const TEST_CREATE_FAIL = 'TEST_CREATE_FAIL'
export const TEST_CREATE_RESET = 'TEST_CREATE_RESET'

export const TEST_UPDATE_REQUEST = 'TEST_UPDATE_REQUEST'
export const TEST_UPDATE_SUCCESS = 'TEST_UPDATE_SUCCESS'
export const TEST_UPDATE_FAIL = 'TEST_UPDATE_FAIL'
export const TEST_UPDATE_RESET = 'TEST_UPDATE_RESET'

export const TEST_CREATE_REVIEW_REQUEST = 'TEST_CREATE_REVIEW_REQUEST'
export const TEST_CREATE_REVIEW_SUCCESS = 'TEST_CREATE_REVIEW_SUCCESS'
export const TEST_CREATE_REVIEW_FAIL = 'TEST_CREATE_REVIEW_FAIL'
export const TEST_CREATE_REVIEW_RESET = 'TEST_CREATE_REVIEW_RESET'

export const TEST_TOP_REQUEST = 'TEST_TOP_REQUEST'
export const TEST_TOP_SUCCESS = 'TEST_TOP_SUCCESS'
export const TEST_TOP_FAIL = 'TEST_TOP_FAIL'
